package(default_visibility = ["//visibility:public"])

_COPTS = [
    "-std=gnu++2a",
]

# cc_library(
#     name = "terp",
#     srcs = [
#         "terp.cc",
#     ],
#     hdrs = [
#         "result_message.h",
#         "result.h",
#         "terp.h",
#     ],
#     copts = _COPTS,
# )

# cc_binary(
#     name = "main",
#     srcs = [
#         "main.cc",
#     ],
#     copts = _COPTS,
#     deps = [
#         ":terp",
#     ],
# )
