# Copyright (c) 2021 The Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Authors: liubang (it.liubang@gmail.com)
# Created: 2021/01/30 16:36

package(default_visibility = ["//visibility:public"])

_COPTS = [
    "-std=gnu++2a",
]

# cc_library(
#     name = "terp",
#     srcs = [
#         "terp.cc",
#     ],
#     hdrs = [
#         "result_message.h",
#         "result.h",
#         "terp.h",
#     ],
#     copts = _COPTS,
# )

# cc_binary(
#     name = "main",
#     srcs = [
#         "main.cc",
#     ],
#     copts = _COPTS,
#     deps = [
#         ":terp",
#     ],
# )
