cc_binary(
    name = "test_signal",
    srcs = ["test_signal.cc"],
)

cc_binary(
    name = "test_oop",
    srcs = [
        "test_oop.cc",
    ],
)

cc_binary(
    name = "test_file_info",
    srcs = [
        "test_file_info.cc",
    ],
    copts = [
        "-std=gnu++14",
    ],
)

cc_binary(
    name = "test_string",
    srcs = [
        "test_string.cc",
    ],
    copts = [
        "-std=gnu++14",
    ],
)

cc_binary(
    name = "context",
    srcs = [
        "context.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
)

cc_binary(
    name = "test_hash",
    srcs = [
        "test_hash.cc",
        "hash.h",
        "encoding.h",
    ],
    copts = [
        "-std=gnu++17",
    ],
)

cc_binary(
    name = "named_parameters",
    srcs = [
        "named_parameters.cc",
    ],
    copts = [
        "-std=gnu++2a",
    ],
    deps = [
        "@boost//:headers",
    ],
)

cc_binary(
    name = "partial_function",
    srcs = [
        "partial_function.cc",
    ],
    copts = [
        "-std=gnu++2a",
    ],
)

cc_binary(
    name = "partial_application",
    srcs = [
        "partial_application.cc",
    ],
    copts = [
        "-std=gnu++2a",
    ],
)

cc_binary(
    name = "curry_function",
    srcs = [
        "curry_function.cc",
    ],
    copts = [
        "-std=gnu++2a",
    ],
)
