cc_library(
    name = "db_engine",
    srcs = [
        "db_engine.cc",
    ],
    hdrs = [
        "db_engine.h",
        "key.h",
        "val.h",
    ],
    deps = [
        "@rocksdb//:rocksdb",
        "@msgpack//:msgpack",
    ],
)
