# MIT krb5kdc 配置（服务端，仅 KDC 容器使用）
[kdcdefaults]
    kdc_ports = 88
    kdc_tcp_ports = 88

[realms]
    LAB.LOCAL = {
        database_name = /var/lib/krb5kdc/principal
        acl_file = /etc/krb5kdc/kadm5.acl
        key_stash_file = /etc/krb5kdc/stash
        max_life = 10h 0m 0s
        max_renewable_life = 7d 0h 0m 0s
        supported_enctypes = aes256-cts-hmac-sha1-96:normal aes128-cts-hmac-sha1-96:normal
        # 开启预认证（生产默认姿势）：kinit 时先证明知道密码，防止离线爆破
        default_principal_flags = +preauth
    }

[logging]
    kdc = STDERR
    admin_server = STDERR
    default = STDERR
