cc_binary(
    name = "factorial",
    srcs = [
        "factorial.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
)

cc_binary(
    name = "prime_print",
    srcs = [
        "prime_print.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
)
