// Copyright (c) 2026 The Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Authors: liubang (it.liubang@gmail.com)
// Created: 2026/08/06

// Package imagegen implements the generate_image tool: text-to-image via an
// images.Generator (OpenAI Images API), with the generated bytes persisted
// into the artifact store; the agent loop materializes a derived inline
// image at the egress so a vision-capable model can review its own output.
package imagegen

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/liubang/playground/go/pl/loom/internal/domain"
	"github.com/liubang/playground/go/pl/loom/internal/media"
	"github.com/liubang/playground/go/pl/loom/internal/model/images"
	"github.com/liubang/playground/go/pl/loom/internal/tool/toolkit"
)

const (
	// maxPromptRunes bounds the prompt text, matching the schema's
	// maxLength (JSON Schema counts characters, not bytes); image APIs
	// reject very long prompts anyway (gpt-image caps at 32000 chars), and
	// the approval dialog renders the prompt inline.
	maxPromptRunes      = 4096
	approvalPromptRunes = 80
)

// Options pins the deployment-level generation parameters. The model facing
// schema only exposes prompt (+ optional size/quality overrides); the model
// name itself is never model-controllable.
type Options struct {
	// Model is the pinned image model (e.g. "gpt-image-2"); required.
	Model string
	// Size/Quality are the defaults applied when the call leaves them
	// unset; empty means "auto".
	Size    string
	Quality string
}

type generateImageArgs struct {
	Prompt  string `json:"prompt"`
	Size    string `json:"size,omitempty"`
	Quality string `json:"quality,omitempty"`
}

type generateImageOutput struct {
	MediaType     string              `json:"media_type"`
	Bytes         int                 `json:"bytes"`
	Artifact      *domain.ArtifactRef `json:"artifact,omitempty"`
	RevisedPrompt string              `json:"revised_prompt,omitempty"`
	Note          string              `json:"note"`
}

// GenerateImageTool implements generate_image. The artifact store is
// required: the generated image is persisted as an artifact (the UI
// renders the reference for the user) and materialized into a derived
// inline image for the model at the egress (media.Materialize) — nothing
// is ever inlined into the transcript.
type GenerateImageTool struct {
	base      baseTool
	gen       images.Generator
	artifacts domain.ArtifactStore
	opts      Options
}

// NewGenerateImageTool creates the tool. gen must be non-nil; opts.Model is
// required so the wire model can never be influenced by tool arguments.
func NewGenerateImageTool(gen images.Generator, artifacts domain.ArtifactStore, opts Options) (*GenerateImageTool, error) {
	if gen == nil {
		return nil, domain.NewError(domain.ErrInvalidInput, "image generator is required")
	}
	if artifacts == nil {
		return nil, domain.NewError(domain.ErrInvalidInput, "image artifact store is required")
	}
	if strings.TrimSpace(opts.Model) == "" {
		return nil, domain.NewError(domain.ErrInvalidInput, "image model is required")
	}
	if opts.Size != "" && !images.ValidSize(opts.Size) {
		return nil, domain.NewError(domain.ErrInvalidInput, fmt.Sprintf("default size %q is not supported", opts.Size))
	}
	if opts.Quality != "" && !images.ValidQuality(opts.Quality) {
		return nil, domain.NewError(domain.ErrInvalidInput, fmt.Sprintf("default quality %q is not supported", opts.Quality))
	}
	base, err := newBaseTool(domain.ToolDefinition{
		Name: "generate_image",
		Description: "Generate a raster image from a text prompt with the configured image model. " +
			"Use it when the user asks you to create a bitmap visual (illustration, photo-style asset, mockup, " +
			"texture, sprite, cover, infographic) rather than code-native output; do NOT use it for diagrams or " +
			"icons better produced as SVG/HTML/CSS. Each call produces one image and incurs provider cost, so " +
			"batch requests need one call per asset. The generated image is persisted as an artifact, displayed " +
			"to the user, and returned inline so you can review it; to iterate, call again with an adjusted prompt. " +
			"size and quality default to the configured values and rarely need overriding.",
		InputSchema:  json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"prompt":{"type":"string","minLength":1,"maxLength":4096},"size":{"type":"string","enum":["auto","1024x1024","1536x1024","1024x1536"]},"quality":{"type":"string","enum":["auto","low","medium","high"]}},"required":["prompt"]}`),
		OutputSchema: json.RawMessage(`{"type":"object","description":"JSON header (media type, byte size, artifact reference, revised prompt) followed by an artifact reference to the image"}`),
		Capabilities: []domain.Capability{domain.CapNetworkConnect},
		Source:       domain.ToolSourceBuiltin,
	})
	if err != nil {
		return nil, err
	}
	return &GenerateImageTool{base: base, gen: gen, artifacts: artifacts, opts: opts}, nil
}

func (t *GenerateImageTool) Definition() domain.ToolDefinition {
	return t.base.Def
}

// ConcurrentSafe implements domain.ConcurrentSafely: generations are
// independent and artifact staging uses per-call private files.
func (t *GenerateImageTool) ConcurrentSafe() bool { return true }

func (t *GenerateImageTool) Prepare(ctx context.Context, call domain.ToolCall) (domain.PreparedCall, error) {
	args, err := toolkit.DecodeStrict[generateImageArgs](call.Arguments)
	if err != nil {
		return domain.PreparedCall{}, err
	}
	args, err = t.validateArgs(args)
	if err != nil {
		return domain.PreparedCall{}, err
	}

	canonical, err := json.Marshal(args)
	if err != nil {
		return domain.PreparedCall{}, domain.NewError(domain.ErrInternal, "failed to encode canonical arguments", domain.WithCause(err))
	}
	approvalDesc := fmt.Sprintf("Generate image (%s): %s", t.opts.Model, truncateRunes(strings.TrimSpace(args.Prompt), approvalPromptRunes))
	return t.base.PrepareCall(ctx, call, canonical, toolkit.PrepareOptions{ApprovalDesc: approvalDesc})
}

func (t *GenerateImageTool) Execute(ctx context.Context, prepared domain.PreparedCall) domain.ToolResult {
	startedAt := time.Now()
	if err := t.base.VerifyPreparedCall(prepared); err != nil {
		return toolkit.ErrorResult(prepared.Call.ID, startedAt, err)
	}
	args, err := toolkit.DecodeStrict[generateImageArgs](prepared.Call.Arguments)
	if err != nil {
		return toolkit.ErrorResult(prepared.Call.ID, startedAt, err)
	}
	if args, err = t.validateArgs(args); err != nil {
		return toolkit.ErrorResult(prepared.Call.ID, startedAt, err)
	}
	if err := ctx.Err(); err != nil {
		return toolkit.ErrorResult(prepared.Call.ID, startedAt, err)
	}

	res, err := t.gen.Generate(ctx, images.GenerateRequest{
		Model:   t.opts.Model,
		Prompt:  args.Prompt,
		Size:    orDefault(args.Size, t.opts.Size),
		Quality: orDefault(args.Quality, t.opts.Quality),
	})
	if err != nil {
		return toolkit.ErrorResult(prepared.Call.ID, startedAt, err)
	}

	out := generateImageOutput{
		MediaType:     res.MediaType,
		Bytes:         len(res.Data),
		RevisedPrompt: res.RevisedPrompt,
	}

	ref, err := media.StoreImage(ctx, t.artifacts, res.Data)
	if err != nil {
		return toolkit.ErrorResult(prepared.Call.ID, startedAt, err)
	}
	out.Artifact = &ref
	out.Note = "The image is persisted as an artifact, already displayed to the user, and attached for your " +
		"review. Do not embed it as a markdown link in your reply. To iterate, call generate_image again " +
		"with an adjusted prompt."

	header, err := json.Marshal(out)
	if err != nil {
		return toolkit.ErrorResult(prepared.Call.ID, startedAt, domain.NewError(domain.ErrInternal, "failed to encode tool output", domain.WithCause(err)))
	}
	// Text header first, matching the view_image result layout (header +
	// image reference part).
	content := []domain.ContentPart{
		{Kind: domain.PartText, Text: string(header)},
		{Kind: domain.PartArtifact, Artifact: &ref},
	}

	finishedAt := time.Now()
	return domain.ToolResult{
		CallID:     prepared.Call.ID,
		Status:     domain.ToolStatusSuccess,
		Content:    content,
		StartedAt:  startedAt,
		FinishedAt: finishedAt,
	}
}

// validateArgs normalizes and validates the call; it is side-effect-free.
func (t *GenerateImageTool) validateArgs(args generateImageArgs) (generateImageArgs, error) {
	args.Prompt = strings.TrimSpace(args.Prompt)
	if args.Prompt == "" {
		return generateImageArgs{}, domain.NewError(domain.ErrInvalidInput, "prompt is required")
	}
	if utf8.RuneCountInString(args.Prompt) > maxPromptRunes {
		return generateImageArgs{}, domain.NewError(domain.ErrInvalidInput,
			fmt.Sprintf("prompt exceeds the %d character limit", maxPromptRunes))
	}
	if args.Size != "" && !images.ValidSize(args.Size) {
		return generateImageArgs{}, domain.NewError(domain.ErrInvalidInput, fmt.Sprintf("size must be one of auto, 1024x1024, 1536x1024, 1024x1536; got %q", args.Size))
	}
	if args.Quality != "" && !images.ValidQuality(args.Quality) {
		return generateImageArgs{}, domain.NewError(domain.ErrInvalidInput, fmt.Sprintf("quality must be one of auto, low, medium, high; got %q", args.Quality))
	}
	return args, nil
}

func orDefault(value, fallback string) string {
	if value != "" {
		return value
	}
	return fallback
}

func truncateRunes(s string, max int) string {
	runes := []rune(s)
	if len(runes) <= max {
		return s
	}
	return string(runes[:max]) + "…"
}
