// Copyright (c) 2026 The Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Authors: liubang (it.liubang@gmail.com)
// Created: 2026/08/06

// Package imagegen implements the generate_image tool: text-to-image via an
// images.Generator (OpenAI Images API), with the generated bytes persisted
// into the artifact store and the image returned inline so a vision-capable
// model can review its own output.
package imagegen

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/liubang/playground/go/pl/loom/internal/domain"
	"github.com/liubang/playground/go/pl/loom/internal/model/images"
)

const (
	// maxPromptRunes bounds the prompt text, matching the schema's
	// maxLength (JSON Schema counts characters, not bytes); image APIs
	// reject very long prompts anyway (gpt-image caps at 32000 chars), and
	// the approval dialog renders the prompt inline.
	maxPromptRunes = 4096
	// maxInlineImageBytes mirrors view_image: base64 inflates by 4/3 and
	// Anthropic caps a single image block at 5MB on the wire, so 3.5MB raw
	// stays below the strictest provider limit. Larger images are still
	// persisted as artifacts, just not inlined into the transcript.
	maxInlineImageBytes = 3584 << 10
	approvalPromptRunes = 80
)

// Options pins the deployment-level generation parameters. The model facing
// schema only exposes prompt (+ optional size/quality overrides); the model
// name itself is never model-controllable.
type Options struct {
	// Model is the pinned image model (e.g. "gpt-image-2"); required.
	Model string
	// Size/Quality are the defaults applied when the call leaves them
	// unset; empty means "auto".
	Size    string
	Quality string
}

type generateImageArgs struct {
	Prompt  string `json:"prompt"`
	Size    string `json:"size,omitempty"`
	Quality string `json:"quality,omitempty"`
}

type generateImageOutput struct {
	MediaType     string              `json:"media_type"`
	Bytes         int                 `json:"bytes"`
	Artifact      *domain.ArtifactRef `json:"artifact,omitempty"`
	RevisedPrompt string              `json:"revised_prompt,omitempty"`
	Note          string              `json:"note"`
}

// GenerateImageTool implements generate_image. A nil artifact store disables
// artifact persistence (the image is then only returned inline).
type GenerateImageTool struct {
	base      baseTool
	gen       images.Generator
	artifacts domain.ArtifactStore
	opts      Options
}

// NewGenerateImageTool creates the tool. gen must be non-nil; opts.Model is
// required so the wire model can never be influenced by tool arguments.
func NewGenerateImageTool(gen images.Generator, artifacts domain.ArtifactStore, opts Options) (*GenerateImageTool, error) {
	if gen == nil {
		return nil, domain.NewError(domain.ErrInvalidInput, "image generator is required")
	}
	if strings.TrimSpace(opts.Model) == "" {
		return nil, domain.NewError(domain.ErrInvalidInput, "image model is required")
	}
	if opts.Size != "" && !images.ValidSize(opts.Size) {
		return nil, domain.NewError(domain.ErrInvalidInput, fmt.Sprintf("default size %q is not supported", opts.Size))
	}
	if opts.Quality != "" && !images.ValidQuality(opts.Quality) {
		return nil, domain.NewError(domain.ErrInvalidInput, fmt.Sprintf("default quality %q is not supported", opts.Quality))
	}
	base, err := newBaseTool(domain.ToolDefinition{
		Name: "generate_image",
		Description: "Generate a raster image from a text prompt with the configured image model. " +
			"Use it when the user asks you to create a bitmap visual (illustration, photo-style asset, mockup, " +
			"texture, sprite, cover, infographic) rather than code-native output; do NOT use it for diagrams or " +
			"icons better produced as SVG/HTML/CSS. Each call produces one image and incurs provider cost, so " +
			"batch requests need one call per asset. The generated image is persisted as an artifact, displayed " +
			"to the user, and returned inline so you can review it; to iterate, call again with an adjusted prompt. " +
			"size and quality default to the configured values and rarely need overriding.",
		InputSchema:  json.RawMessage(`{"type":"object","additionalProperties":false,"properties":{"prompt":{"type":"string","minLength":1,"maxLength":4096},"size":{"type":"string","enum":["auto","1024x1024","1536x1024","1024x1536"]},"quality":{"type":"string","enum":["auto","low","medium","high"]}},"required":["prompt"]}`),
		OutputSchema: json.RawMessage(`{"type":"object","description":"JSON header (media type, byte size, artifact reference, revised prompt) followed by the image as an inline image content part"}`),
		Capabilities: []domain.Capability{domain.CapNetworkConnect},
		Source:       domain.ToolSourceBuiltin,
	})
	if err != nil {
		return nil, err
	}
	return &GenerateImageTool{base: base, gen: gen, artifacts: artifacts, opts: opts}, nil
}

func (t *GenerateImageTool) Definition() domain.ToolDefinition {
	return t.base.def
}

// ConcurrentSafe implements domain.ConcurrentSafely: generations are
// independent and artifact staging uses per-call private files.
func (t *GenerateImageTool) ConcurrentSafe() bool { return true }

func (t *GenerateImageTool) Prepare(ctx context.Context, call domain.ToolCall) (domain.PreparedCall, error) {
	args, err := decodeStrict[generateImageArgs](call.Arguments)
	if err != nil {
		return domain.PreparedCall{}, err
	}
	args, err = t.validateArgs(args)
	if err != nil {
		return domain.PreparedCall{}, err
	}

	canonical, err := json.Marshal(args)
	if err != nil {
		return domain.PreparedCall{}, domain.NewError(domain.ErrInternal, "failed to encode canonical arguments", domain.WithCause(err))
	}
	approvalDesc := fmt.Sprintf("Generate image (%s): %s", t.opts.Model, truncateRunes(strings.TrimSpace(args.Prompt), approvalPromptRunes))
	return t.base.prepareCall(ctx, call, canonical, approvalDesc)
}

func (t *GenerateImageTool) Execute(ctx context.Context, prepared domain.PreparedCall) domain.ToolResult {
	startedAt := time.Now()
	if err := t.base.verifyPreparedCall(prepared); err != nil {
		return errorResult(prepared.Call.ID, startedAt, err)
	}
	args, err := decodeStrict[generateImageArgs](prepared.Call.Arguments)
	if err != nil {
		return errorResult(prepared.Call.ID, startedAt, err)
	}
	if args, err = t.validateArgs(args); err != nil {
		return errorResult(prepared.Call.ID, startedAt, err)
	}
	if err := ctx.Err(); err != nil {
		return errorResult(prepared.Call.ID, startedAt, err)
	}

	res, err := t.gen.Generate(ctx, images.GenerateRequest{
		Model:   t.opts.Model,
		Prompt:  args.Prompt,
		Size:    orDefault(args.Size, t.opts.Size),
		Quality: orDefault(args.Quality, t.opts.Quality),
	})
	if err != nil {
		return errorResult(prepared.Call.ID, startedAt, err)
	}

	out := generateImageOutput{
		MediaType:     res.MediaType,
		Bytes:         len(res.Data),
		RevisedPrompt: res.RevisedPrompt,
	}

	content := make([]domain.ContentPart, 0, 3)
	if ref, ok := t.storeArtifact(ctx, res.Data); ok {
		ref.MediaType = res.MediaType
		out.Artifact = &ref
		content = append(content, domain.ContentPart{Kind: domain.PartArtifact, Artifact: &ref})
	}
	inlined := len(res.Data) <= maxInlineImageBytes
	switch {
	case out.Artifact != nil && inlined:
		out.Note = "The image is persisted as an artifact, already displayed to the user, and attached inline below " +
			"for your review. Do not embed it as a markdown link in your reply. To iterate, call generate_image again " +
			"with an adjusted prompt."
	case out.Artifact != nil:
		out.Note = "The image is persisted as an artifact and already displayed to the user; it exceeds the inline " +
			"size limit, so it is not attached for your review. To iterate, call generate_image again with an " +
			"adjusted prompt."
	case inlined:
		out.Note = "The image is attached inline below for your review and is already displayed to the user. " +
			"To iterate, call generate_image again with an adjusted prompt."
	default:
		out.Note = "The image was generated but exceeds the inline size limit and no artifact store is configured, " +
			"so it could not be returned. To iterate, call generate_image again with an adjusted prompt."
	}

	header, err := json.Marshal(out)
	if err != nil {
		return errorResult(prepared.Call.ID, startedAt, domain.NewError(domain.ErrInternal, "failed to encode tool output", domain.WithCause(err)))
	}
	// Text header first, matching the view_image result layout (header +
	// image part).
	content = append([]domain.ContentPart{{Kind: domain.PartText, Text: string(header)}}, content...)
	if inlined {
		content = append(content, domain.ContentPart{Kind: domain.PartImage, Image: &domain.ImageContent{
			MediaType: res.MediaType,
			Data:      base64.StdEncoding.EncodeToString(res.Data),
		}})
	}

	finishedAt := time.Now()
	return domain.ToolResult{
		CallID:     prepared.Call.ID,
		Status:     domain.ToolStatusSuccess,
		Content:    content,
		StartedAt:  startedAt,
		FinishedAt: finishedAt,
	}
}

// validateArgs normalizes and validates the call; it is side-effect-free.
func (t *GenerateImageTool) validateArgs(args generateImageArgs) (generateImageArgs, error) {
	args.Prompt = strings.TrimSpace(args.Prompt)
	if args.Prompt == "" {
		return generateImageArgs{}, domain.NewError(domain.ErrInvalidInput, "prompt is required")
	}
	if utf8.RuneCountInString(args.Prompt) > maxPromptRunes {
		return generateImageArgs{}, domain.NewError(domain.ErrInvalidInput,
			fmt.Sprintf("prompt exceeds the %d character limit", maxPromptRunes))
	}
	if args.Size != "" && !images.ValidSize(args.Size) {
		return generateImageArgs{}, domain.NewError(domain.ErrInvalidInput, fmt.Sprintf("size must be one of auto, 1024x1024, 1536x1024, 1024x1536; got %q", args.Size))
	}
	if args.Quality != "" && !images.ValidQuality(args.Quality) {
		return generateImageArgs{}, domain.NewError(domain.ErrInvalidInput, fmt.Sprintf("quality must be one of auto, low, medium, high; got %q", args.Quality))
	}
	return args, nil
}

// storeArtifact persists the generated bytes; failure degrades to "no
// artifact" rather than failing the call — the inline image still carries
// the result to the model and the user.
func (t *GenerateImageTool) storeArtifact(ctx context.Context, data []byte) (domain.ArtifactRef, bool) {
	if t.artifacts == nil {
		return domain.ArtifactRef{}, false
	}
	stage, err := t.artifacts.Begin(ctx)
	if err != nil {
		return domain.ArtifactRef{}, false
	}
	if _, err := stage.Write(data); err != nil {
		_ = stage.Abort()
		return domain.ArtifactRef{}, false
	}
	if stage.Truncated() {
		_ = stage.Abort()
		return domain.ArtifactRef{}, false
	}
	ref, err := stage.Commit(ctx)
	if err != nil {
		return domain.ArtifactRef{}, false
	}
	return ref, true
}

func orDefault(value, fallback string) string {
	if value != "" {
		return value
	}
	return fallback
}

func truncateRunes(s string, max int) string {
	runes := []rune(s)
	if len(runes) <= max {
		return s
	}
	return string(runes[:max]) + "…"
}
