#======================================================================
#
# BUILD -
#
# Created by liubang on 2023/05/26 16:42
# Last Modified: 2023/05/26 16:42
#
#======================================================================

cc_library(
    name = "fs",
    srcs = ["posix_fs.cpp"],
    hdrs = ["fs.h"],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
    deps = [
        "//cpp/tools",
    ],
)
