coordinator=true
node.internal-address=trino-coordinator
discovery.uri=http://trino-coordinator:8099
http-server.http.port=8099
internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}
plugin.dir=/usr/lib/trino/plugin
