#======================================================================
#
# BUILD -
#
# Created by liubang on 2023/05/21 22:59
# Last Modified: 2023/05/21 22:59
#
#======================================================================

cc_library(
    name = "yabf",
    hdrs = ["yabf.h"],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "bf",
    srcs = ["bf.cpp"],
    copts = [
        "-std=c++20",
    ],
    visibility = ["//visibility:public"],
)
