# Copyright (c) 2024 The Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Authors: liubang (it.liubang@gmail.com)

load("@rules_bison//bison:bison.bzl", "bison", "bison_cc_library")
load("@rules_flex//flex:flex.bzl", "flex", "flex_cc_library")

# flex(
#     name = "flux_lexer",
#     src = "flux_lexer.l",
# )
#
# bison(
#     name = "flux_parser",
#     src = "flux_parser.y",
# )
#
# cc_library(
#     name = "flux_common",
#     srcs = [
#         "flux.c",
#         ":flux_lexer",
#         ":flux_parser",
#     ],
#     hdrs = ["flux.h"],
#     includes = ["."],
# )
#
# cc_binary(
#     name = "flux",
#     srcs = ["main.c"],
#     copts = ["-std=c11"],
#     deps = [
#         ":calc_common",
#     ],
# )
