#======================================================================
#
# BUILD -
#
# Created by liubang on 2023/05/25 00:02
# Last Modified: 2023/05/25 00:02
#
#======================================================================

load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "sensor",
    srcs = ["sensor.proto"],
)
