#======================================================================
#
# BUILD -
#
# Created by liubang on 2023/09/28 14:01
# Last Modified: 2023/09/28 14:01
#
#======================================================================
load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "log",
    srcs = ["log.proto"],
)
