cc_binary(
    name = "test",
    srcs = [
        "test.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
    linkopts = [
        "-lstdc++",
        "-static",
    ],
    deps = [
        "@cityhash",
    ],
)
