#======================================================================
#
# BUILD -
#
# Created by liubang on 2023/05/26 00:42
# Last Modified: 2023/05/26 00:42
#
#======================================================================

load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_ut",
    srcs = ["test_ut.py"],
)
