coordinator=false
node.internal-address=trino-worker-1
http-server.http.port=8199
discovery.uri=http://trino-coordinator:8099
internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}
plugin.dir=/usr/lib/trino/plugin
