#======================================================================
#
# BUILD -
#
# Created by liubang on 2023/05/21 01:23
# Last Modified: 2023/05/21 01:23
#
#======================================================================

load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = {
        "//cpp/...": "",
    },
)
