workspace(name = "cpp")

load("//third_party:repository.bzl", "external_dependencies", "external_repositories")

external_dependencies()

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

rules_foreign_cc_dependencies()

external_repositories()
