cc_library(
    name = "bloom_filter",
    srcs = [
        "bloom_filter.cc",
    ],
    hdrs = [
        "bloom_filter.h",
    ],
    copts = [
        "-std=gnu++17",
    ],
    deps = [
        "//highkyck/hash:hash",
    ],
    visibility = ["//visibility:public"],
)
