#======================================================================
#
# BUILD -
#
# Created by liubang on 2023/06/13 10:28
# Last Modified: 2023/06/13 10:28
#
#======================================================================

load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "ping",
    srcs = ["main.go"],
    # importpath = "github.com/playground/go/tools/ping/main",
    visibility = ["//visibility:public"],
)
