#======================================================================
#
# BUILD -
#
# Created by liubang on 2023/05/21 01:00
# Last Modified: 2023/05/21 01:00
#
#======================================================================

cc_library(
    name = "meta",
    hdrs = glob(["*.h"]),
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
)
