#======================================================================
#
# BUILD -
#
# Created by liubang on 2023/05/21 01:37
# Last Modified: 2023/05/21 01:37
#
#======================================================================
cc_library(
    name = "arena",
    srcs = [
        "arena.cpp",
    ],
    hdrs = [
        "arena.h",
    ],
    copts = [
        "-std=c++20",
    ],
    visibility = ["//visibility:public"],
)
