cc_binary(
    name = "demo1",
    srcs = [
        "demo1.cc",
        "demo1.h",
    ],
    copts = [
        "-std=c++17",
    ],
)

cc_binary(
    name = "print",
    srcs = [
        "print.cpp",
        "print.h",
    ],
    copts = [
        "-std=c++20",
    ],
)

cc_binary(
    name = "traits",
    srcs = [
        "traits.cpp",
        "traits.h",
        "traits_test.h",
    ],
    copts = [
        "-std=c++20",
    ],
)

cc_binary(
    name = "expression",
    srcs = [
        "expression.h",
        "expression_test.cpp",
        "traits.h",
    ],
    copts = [
        "-std=c++20",
    ],
)
