cc_binary(
    name = "demo1",
    srcs = [
        "demo1.cc",
        "demo1.h",
    ],
    copts = [
        "-std=c++17",
    ],
)

cc_binary(
    name = "print",
    srcs = [
        "print.cpp",
        "print.h",
    ],
    copts = [
        "-std=c++20",
    ],
)
