#======================================================================
#
# BUILD -
#
# Created by liubang on 2023/07/16 23:38
# Last Modified: 2023/07/16 23:38
#
#======================================================================

load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "strings",
    srcs = ["main.go"],
    visibility = ["//visibility:public"],
)
