cc_test(
    name = "766.toeplitz-matrix",
    srcs = [
        "766.toeplitz-matrix.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
    deps = [
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "485.max-consecutive-ones",
    srcs = [
        "485.max-consecutive-ones.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
    deps = [
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "463.island-perimeter",
    srcs = [
        "463.island-perimeter.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
    deps = [
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "1052.grumpy-bookstore-owner",
    srcs = [
        "1052.grumpy-bookstore-owner.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
    deps = [
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "832.flipping-an-image",
    srcs = [
        "832.flipping-an-image.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
    deps = [
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "867.transpose-matrix",
    srcs = [
        "867.transpose-matrix.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
    deps = [
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "1047.remove-all-adjacent-duplicates-in-string",
    srcs = [
        "1047.remove-all-adjacent-duplicates-in-string.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
    deps = [
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "224.basic-calculator",
    srcs = [
        "224.basic-calculator.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
    deps = [
        "@gtest//:gtest_main",
    ],
)
