cc_test(
    name = "766.toeplitz-matrix",
    srcs = [
        "766.toeplitz-matrix.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
    deps = [
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "485.max-consecutive-ones",
    srcs = [
        "485.max-consecutive-ones.cc",
    ],
    copts = [
        "-std=gnu++17",
    ],
    deps = [
        "@gtest//:gtest_main",
    ],
)
