#!/bin/bash
# Copyright (c) 2026 The Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Authors: liubang (it.liubang@gmail.com)
# Created: 2026/09/13 19:10
#
# clangd_doctor.sh -- one-shot health check for clangd / IDE diagnostics.
#
# compile_commands.json here is generated by hedron and carries paths pointing
# into bazel-out/... and the Xcode SDK. What clangd actually compiles with is
# that command *plus* any project-level .clangd and user-level
# clangd/config.yaml overlays. If either the database or an overlay goes stale,
# clangd emits nonsense diagnostics on perfectly good code, e.g.
#
#   unknown type name '__uint32_t'
#   member reference base type 'std::string_view' (aka 'int') is not a ...
#   unknown type name 'size_t'; did you mean 'ssize_t'?
#
# The classic trigger: `brew upgrade llvm` replaces lib/clang/<N> with a new
# version while a config file still hard-codes the old <N> (see the 2026-09
# incident this script was written for).
#
# Usage:
#   tools/clangd_doctor.sh [--clangd PATH] [--no-probe] [source file]
#
# With no source file it picks a recently modified .cpp out of the database.
# Exit codes: 0 = clean (warnings allowed), 1 = at least one FAIL, 2 = usage.
#
# Requires bash 3.2+ (macOS system bash), python3 (Xcode command line tools),
# and only BSD/GNU-portable utilities. No network access.

set -u

VERSION="1.0"

# ----------------------------------------------------------------- options
usage() {
    cat <<'EOF'
clangd doctor -- diagnose bogus clangd/IDE diagnostics in this repo.

Usage:
  tools/clangd_doctor.sh [options] [source file]

Options:
  --clangd PATH   clangd binary to inspect (default: auto-detect every
                  known install location and use the first one)
  --no-probe      skip the clangd --check probe (faster, fewer checks)
  --color         force ANSI colors even when stdout is not a TTY
  --no-color      disable ANSI colors (also honors $NO_COLOR)
  -h, --help      show this help

With no source file, a recently modified .cpp is picked from
compile_commands.json and used for the clangd probe.

Exit status: 0 clean, 1 problems found, 2 usage error.
EOF
}

CLANGD_WANT=""
TARGET=""
PROBE=1
NO_COLOR_FLAG=""

while [ "$#" -gt 0 ]; do
    case "$1" in
    --clangd)
        if [ "$#" -lt 2 ]; then
            printf 'clangd_doctor: --clangd needs a path\n' >&2
            exit 2
        fi
        CLANGD_WANT="$2"
        shift 2
        ;;
    --clangd=*)
        CLANGD_WANT="${1#*=}"
        shift
        ;;
    --no-probe)
        PROBE=0
        shift
        ;;
    --no-color)
        NO_COLOR_FLAG=1
        shift
        ;;
    --color)
        FORCE_COLOR=1
        shift
        ;;
    -h | --help)
        usage
        exit 0
        ;;
    -*)
        printf 'clangd_doctor: unknown option: %s\n' "$1" >&2
        usage >&2
        exit 2
        ;;
    *)
        TARGET="$1"
        shift
        ;;
    esac
done

# When --clangd is relative it should resolve against the invocation dir.
if [ -n "$CLANGD_WANT" ] && [ "${CLANGD_WANT#/}" = "$CLANGD_WANT" ]; then
    CLANGD_WANT="$(pwd)/$CLANGD_WANT"
fi

# --------------------------------------------------------------- output
# Pure ASCII output: locale-independent and safe in any terminal.
use_color=1
if [ -n "$NO_COLOR_FLAG" ] || [ -n "${NO_COLOR:-}" ]; then
    use_color=0
elif [ -z "${FORCE_COLOR:-}" ] && { [ ! -t 1 ] || [ "${TERM:-dumb}" = "dumb" ]; }; then
    use_color=0
fi

if [ "$use_color" -eq 0 ]; then
    C_RST=""
    C_BOLD=""
    C_OK=""
    C_WARN=""
    C_FAIL=""
    C_HEAD=""
    C_DIM=""
else
    C_RST=$'\033[0m'
    C_BOLD=$'\033[1m'
    C_OK=$'\033[32m'
    C_WARN=$'\033[33m'
    C_FAIL=$'\033[31m'
    C_HEAD=$'\033[36m'
    C_DIM=$'\033[2m'
fi

OK_N=0
WARN_N=0
FAIL_N=0
DB_FAIL=0 # set when checks in section 2 failed: the database must be rebuilt

title() { # <workspace>
    printf '\n%sclangd doctor%s %s%s%s  %s%s%s\n' \
        "$C_BOLD" "$C_RST" "$C_DIM" "$VERSION" "$C_RST" "$C_DIM" "$1" "$C_RST"
}

section() { # <n> <total> <title>
    printf '\n%s[%s/%s]%s %s%s%s\n' \
        "$C_HEAD" "$1" "$2" "$C_RST" "$C_BOLD" "$3" "$C_RST"
}

kv() { # <label> <value>
    printf '  %s%-10s%s %s\n' "$C_DIM" "$1" "$C_RST" "$2"
}

ok() {
    OK_N=$((OK_N + 1))
    printf '  %sok  %s %s\n' "$C_OK" "$C_RST" "$*"
}

warn() {
    WARN_N=$((WARN_N + 1))
    printf '  %swarn%s %s\n' "$C_WARN" "$C_RST" "$*"
}

fail() {
    FAIL_N=$((FAIL_N + 1))
    printf '  %sfail%s %s\n' "$C_FAIL" "$C_RST" "$*"
}

info() { printf '       %s%s%s\n' "$C_DIM" "$*" "$C_RST"; }

hint() { printf '       %s-> %s%s\n' "$C_DIM" "$*" "$C_RST"; }

render() { # consume "LEVEL<TAB>message" lines emitted by the python helper
    while IFS=$'\t' read -r lvl msg; do
        case "$lvl" in
        OK) ok "$msg" ;;
        WARN) warn "$msg" ;;
        FAIL) fail "$msg" ;;
        HINT) hint "$msg" ;;
        INFO) info "$msg" ;;
        SAMPLE) TARGET="$msg" ;;
        *) info "$msg" ;;
        esac
    done
}

# ------------------------------------------------------------ temp + root
tmp_base="${TMPDIR:-/tmp}"
tmp_base="${tmp_base%/}"
LOG="$(mktemp "${tmp_base}/clangd_doctor.XXXXXX" 2>/dev/null)" || {
    LOG=""
}
if [ -n "$LOG" ]; then
    trap 'rm -f "$LOG"' EXIT INT TERM
fi

if [ -n "${BUILD_WORKSPACE_DIRECTORY:-}" ]; then
    ROOT="$BUILD_WORKSPACE_DIRECTORY" # set by `bazel run`
elif ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" && [ -n "$ROOT" ]; then
    : # git work tree
else
    ROOT="$(pwd)"
fi
cd "$ROOT" 2>/dev/null || {
    printf 'clangd_doctor: cannot enter workspace: %s\n' "$ROOT" >&2
    exit 2
}
# Physical path: /tmp -> /private/tmp and friends make the same tree appear under
# two names, and clangd reports the physical one.
ROOT_PHYS="$(pwd -P)"

title "$ROOT"

# ============================================================ 1. environment
section 1 6 "environment"

kv "workspace" "$ROOT"

if [ -z "$LOG" ]; then
    fail "cannot create a temp file under ${tmp_base}"
    hint "check TMPDIR and its permissions"
fi

# Collect every plausible clangd, so a mismatch with the one the editor uses
# is visible instead of silent.
resolve_link() { # follow symlinks without `readlink -f` (BSD readlink lacks it)
    local p="$1"
    local hops=0
    local t d
    while [ -L "$p" ] && [ "$hops" -lt 10 ]; do
        t="$(readlink "$p")"
        case "$t" in
        /*) p="$t" ;;
        *) p="$(dirname "$p")/$t" ;;
        esac
        hops=$((hops + 1))
    done
    # `pwd -P` collapses ./.. and symlinked directories, so two aliases of the
    # same binary end up as the same string and dedupe works.
    d="$(cd "$(dirname "$p")" 2>/dev/null && pwd -P)" || {
        printf '%s' "$p"
        return 0
    }
    printf '%s/%s' "${d%/}" "$(basename "$p")"
}

# Short version string, whatever the vendor prefix ("Homebrew clangd ...").
version_of() { # <binary>
    local out
    out="$("$1" --version 2>/dev/null | head -n 1 |
        sed -E 's/.*[Vv]ersion ([0-9][0-9.]*).*/\1/')"
    case "$out" in
    "" | *[!0-9.]*) out="unknown" ;;
    esac
    printf '%s' "$out"
}

CAND_ENTRIES="" # "<as-typed path>|<resolved path>" per line
add_candidate() {
    local real
    [ -n "$1" ] || return 0
    if [ ! -f "$1" ] || [ ! -x "$1" ]; then
        return 0 # missing, or a directory
    fi
    real="$(resolve_link "$1")"
    if printf '%s' "$CAND_ENTRIES" | grep -qF -- "|${real}"; then
        return 0
    fi
    CAND_ENTRIES="${CAND_ENTRIES}${1}|${real}"$'\n'
}

for c in "${CLANGD:-}" \
    "$HOME/.local/share/nvim/mason/bin/clangd" \
    "/opt/homebrew/bin/clangd" \
    "/opt/homebrew/opt/llvm/bin/clangd" \
    "/usr/local/bin/clangd" \
    "/usr/local/opt/llvm/bin/clangd" \
    "/usr/bin/clangd"; do
    add_candidate "$c"
done
for c in "$HOME"/.local/share/nvim/mason/packages/clangd/*/bin/clangd; do
    add_candidate "$c"
done
if command -v clangd >/dev/null 2>&1; then
    add_candidate "$(command -v clangd)"
fi

CLANGD="" # resolved path of the selected binary
if [ -n "$CLANGD_WANT" ]; then
    if [ -f "$CLANGD_WANT" ] && [ -x "$CLANGD_WANT" ]; then
        CLANGD="$(resolve_link "$CLANGD_WANT")"
        add_candidate "$CLANGD_WANT" # listed even if the globs missed it
    else
        fail "--clangd is not executable: $CLANGD_WANT"
    fi
elif [ -n "$CAND_ENTRIES" ]; then
    # First entry wins: "<display>|<resolved>" on line 1.
    CLANGD="$(printf '%s' "$CAND_ENTRIES" | head -n 1 | sed -E 's/^[^|]*\|//')"
fi

if [ -n "$CAND_ENTRIES" ]; then
    # Selection is by resolved path, so aliases of the same binary are marked too.
    while IFS='|' read -r disp resolved; do
        [ -n "$disp" ] || continue
        cver="$(version_of "$disp")"
        if [ "$resolved" = "$CLANGD" ]; then
            kv "clangd" "$disp  ($cver)  <- selected"
        else
            kv "" "$disp  ($cver)"
        fi
    done <<<"$CAND_ENTRIES"
    hint "if your editor uses a different one, re-run with --clangd <path>"
elif [ -z "$CLANGD" ]; then
    fail "no clangd found on this machine"
    hint "install one (mason/brew) or pass --clangd /path/to/clangd"
fi

CLANGD_MAJOR=""
if [ -n "$CLANGD" ]; then
    raw="$("$CLANGD" --version 2>/dev/null | head -n 1)"
    if [ -z "$raw" ]; then
        warn "clangd does not report a version (broken install?)"
    fi
    CLANGD_MAJOR="$(printf '%s' "$raw" | sed -E 's/.*clangd version ([0-9]+).*/\1/')"
    case "$CLANGD_MAJOR" in
    "" | *[!0-9]*) CLANGD_MAJOR="" ;;
    esac
fi

if ! command -v python3 >/dev/null 2>&1; then
    fail "python3 not found (needed to inspect compile_commands.json)"
    hint "install the Xcode command line tools: xcode-select --install"
    python3=""
else
    python3="$(command -v python3)"
fi

# ==================================================== 2. compilation database
section 2 6 "compilation database"

if [ -z "$python3" ]; then
    warn "skipped: python3 is unavailable (see above)"
else
    cdb_out="$(
        "$python3" - "$ROOT" "$TARGET" "$ROOT_PHYS" <<'PY'
import json
import os
import shlex
import sys

root, target, root_phys = sys.argv[1], sys.argv[2], sys.argv[3]
roots = [root] if root_phys == root else [root, root_phys]
cdb_path = os.path.join(root, "compile_commands.json")


def emit(level, msg):
    sys.stdout.write("%s\t%s\n" % (level, msg))


if not os.path.isfile(cdb_path):
    emit("FAIL", "compile_commands.json not found in the workspace root")
    emit("HINT", "bazel run //:refresh_compile_commands")
    raise SystemExit(0)

size = os.path.getsize(cdb_path)
with open(cdb_path, encoding="utf-8", errors="replace") as fh:
    text = fh.read()
try:
    db = json.loads(text)
except json.JSONDecodeError:
    start = text.find("[")
    if start < 0:
        emit("FAIL", "compile_commands.json is not valid JSON")
        emit("HINT", "delete it and re-run: bazel run //:refresh_compile_commands")
        raise SystemExit(0)
    emit("WARN", "compile_commands.json has a non-JSON prefix; parsed from the first '['")
    try:
        db = json.loads(text[start:])
    except json.JSONDecodeError:
        emit("FAIL", "compile_commands.json is truncated or corrupt")
        emit("HINT", "bazel run //:refresh_compile_commands")
        raise SystemExit(0)

if not isinstance(db, list) or not db:
    emit("FAIL", "compilation database is empty")
    emit("HINT", "check the targets of refresh_compile_commands in the root BUILD")
    raise SystemExit(0)

emit("OK", "compile_commands.json: %d entries, %.1f MB" % (len(db), size / 1e6))

SKIP_DIRS = {
    "external",
    "bazel-out",
    "bazel-bin",
    "bazel-testlogs",
    "bazel-" + os.path.basename(root),
}


def abspath_of(entry):
    f = entry.get("file", "")
    if os.path.isabs(f):
        return os.path.normpath(f)
    return os.path.normpath(os.path.join(entry.get("directory", root), f))


def is_workspace_source(path):
    """Only sources inside the repo: clangd cannot map cached files to the CDB."""
    for base in roots:
        rel = os.path.relpath(path, base)
        if rel.startswith(".."):
            continue
        if os.path.normpath(rel).split(os.sep)[0] not in SKIP_DIRS:
            return True
    return False


# Pick a probe sample: a small, recently modified workspace .cpp.
if not target:
    sized = []
    for entry in db:
        if not entry.get("file", "").endswith((".cpp", ".cc", ".cxx")):
            continue
        p = abspath_of(entry)
        if not is_workspace_source(p):
            continue
        try:
            if os.path.getsize(p) > 200 * 1024:
                continue
            sized.append((os.path.getmtime(p), p))
        except OSError:
            continue
    if not sized:
        for entry in db:
            p = abspath_of(entry)
            if os.path.isfile(p) and is_workspace_source(p):
                sized.append((os.path.getmtime(p), p))
                break
    if sized:
        sized.sort()
        emit("SAMPLE", sized[-1][1])
        emit("INFO", "no source file given; probing the most recently modified one")

wants = []
if target:
    if os.path.isabs(target):
        wants.append(os.path.normpath(target))
    else:
        wants = [os.path.normpath(os.path.join(base, target)) for base in roots]

entry = None
if wants:
    for cand in db:
        if abspath_of(cand) in wants:
            entry = cand
            break
    if entry is None:
        rel = wants[0]
        for base in roots:
            candidate_rel = os.path.relpath(wants[0], base)
            if not candidate_rel.startswith(".."):
                rel = candidate_rel
                break
        emit("FAIL", "no compile command for %s" % rel)
        emit("HINT", "the file may not belong to //cpp/..., or the database is stale")
        emit("HINT", "bazel run //:refresh_compile_commands")
else:
    for cand in db:
        p = abspath_of(cand)
        if os.path.isfile(p) and is_workspace_source(p):
            entry = cand
            break

if entry is None:
    emit("WARN", "no usable source file to probe; skipping the remaining checks")
    raise SystemExit(0)

# The command directory decides how every relative include path resolves.
directory = entry.get("directory", "")
if os.path.normpath(directory) in [os.path.normpath(r) for r in roots]:
    emit("OK", "command directory matches the workspace root")
else:
    emit("FAIL", "command directory %s differs from the workspace root %s" % (directory, root))
    emit("HINT", "the repo was moved or is reached through a different path")
    emit("HINT", "bazel run //:refresh_compile_commands")

args = entry.get("arguments")
if args is None:
    args = shlex.split(entry.get("command", ""))

# Split the interesting flags out of the command line.
NEEDS_VALUE = {"-I", "-iquote", "-isystem", "-idirafter", "-iframework", "-F", "-isysroot"}
includes = []
sysroots = []
i = 0
while i < len(args):
    a = args[i]
    if a in NEEDS_VALUE and i + 1 < len(args):
        val = args[i + 1]
        (sysroots if a == "-isysroot" else includes).append((a, val))
        i += 2
        continue
    for flag in ("-isysroot", "-isystem", "-iquote", "-I", "-F"):
        if a.startswith(flag) and len(a) > len(flag):
            val = a[len(flag):]
            (sysroots if flag == "-isysroot" else includes).append((flag, val))
            break
    i += 1


def resolve(base, val):
    return os.path.normpath(val if os.path.isabs(val) else os.path.join(base, val))


# A vanished bazel-out configuration directory is the hard signal of a stale DB.
out_roots = []
for _, val in includes:
    marker = "/bazel-out/"
    if val.startswith("bazel-out/"):
        parts = val.split("/")
    elif marker in val:
        parts = val[val.index(marker) + 1:].split("/")
    else:
        continue
    if len(parts) >= 3:
        root_dir = "/".join(parts[:3])
        if root_dir not in out_roots:
            out_roots.append(root_dir)

gone = [r for r in out_roots if not os.path.exists(resolve(directory, r))]
if gone:
    emit("FAIL", "bazel-out directory referenced by the DB is gone: %s" % ", ".join(gone))
    emit("HINT", "bazel clean or a --config switch left the DB pointing at an old output tree")
    emit("HINT", "bazel build //cpp/... && bazel run //:refresh_compile_commands")
elif out_roots:
    emit("OK", "bazel-out directories referenced by the DB exist: %s" % ", ".join(out_roots))

# hedron emits both external/<repo> and bazel-out/.../external/<repo> forms; the
# latter is not always materialised by Bazel, so a missing one is informational.
missing = [(flag, val) for flag, val in includes if not os.path.exists(resolve(directory, val))]
if not includes:
    emit("INFO", "the sample command has no include flags to check")
elif len(missing) == len(includes):
    emit("FAIL", "all %d include paths are missing" % len(includes))
    emit("HINT", "bazel build //cpp/... && bazel run //:refresh_compile_commands")
elif missing:
    emit("INFO", "%d/%d include paths missing (usually unmaterialised bazel-out mirrors)"
         % (len(missing), len(includes)))
    emit("INFO", "e.g. %s %s" % missing[0])
else:
    emit("OK", "all %d include paths exist" % len(includes))

if not sysroots:
    emit("INFO", "the sample command has no -isysroot, using the toolchain default")
for _, val in sysroots:
    if os.path.exists(resolve(directory, val)):
        emit("OK", "-isysroot exists: %s" % val)
    else:
        emit("FAIL", "-isysroot does not exist: %s" % val)
        emit("HINT", "Xcode or the command line tools moved; re-select with xcode-select")

# A BUILD file newer than the DB may mean changed deps/copts are not reflected.
try:
    cdb_mtime = os.path.getmtime(cdb_path)
    extra_skip = SKIP_DIRS | {"node_modules", "dist", "build"}
    newer = []
    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        dirnames[:] = [
            d for d in dirnames if not d.startswith(".") and d not in extra_skip
        ]
        for name in filenames:
            if name in ("BUILD", "BUILD.bazel", "MODULE.bazel"):
                p = os.path.join(dirpath, name)
                try:
                    if os.path.getmtime(p) > cdb_mtime:
                        newer.append(os.path.relpath(p, root))
                except OSError:
                    pass
        if len(newer) > 20:
            break
    if newer:
        emit("WARN", "%d BUILD file(s) newer than the DB, e.g. %s" % (len(newer), newer[0]))
        emit("HINT", "re-generate after changing deps or copts")
    else:
        emit("OK", "no BUILD file is newer than the DB")
except OSError as exc:
    emit("WARN", "cannot compare BUILD mtimes with the DB: %s" % exc)
PY
    )"
    fail_before=$FAIL_N
    render <<<"$cdb_out"
    if [ "$FAIL_N" -gt "$fail_before" ]; then
        DB_FAIL=1 # the database itself needs regenerating
    fi
fi

# ======================================================= 3. workspace symlinks
section 3 6 "workspace symlinks"

for link in bazel-out bazel-bin bazel-testlogs; do
    if [ -L "$link" ]; then
        target_of="$(readlink "$link")"
        if [ -e "$link" ]; then
            ok "${link} -> ${target_of}"
        else
            fail "${link} is a dangling symlink -> ${target_of}"
            hint "output_base moved (bazel clean / different user); rebuild to restore"
        fi
    elif [ -d "$link" ]; then
        ok "${link} is a real directory"
    else
        info "${link} not present (this checkout has not been built here yet)"
    fi
done

# ============================================== 4. effective clangd compile env
section 4 6 "effective clangd compile environment"

if [ "$PROBE" -eq 0 ]; then
    info "skipped (--no-probe)"
elif [ -z "$LOG" ]; then
    info "skipped (no temp file available for the probe log)"
elif [ -z "$CLANGD" ]; then
    fail "skipped: no clangd to probe with"
elif [ ! -f "$TARGET" ]; then
    if [ -n "$TARGET" ]; then
        fail "probe source does not exist: $TARGET"
    else
        info "skipped (no source file available to probe)"
    fi
else
    info "probing ${TARGET#"$ROOT"/} (this takes a couple of seconds)"

    "$CLANGD" --check="$TARGET" --log=info >"$LOG" 2>&1 || true

    if ! grep -q 'Entering check mode' "$LOG"; then
        fail "clangd --check produced no usable log"
        hint "run it by hand: $CLANGD --check=$TARGET --log=info"
        if [ -s "$LOG" ]; then
            tail -n 3 "$LOG" | while IFS= read -r l; do info "$l"; done
        fi
    fi

    # Which compilation database did clangd actually load?
    loaded_db="$(grep -oE 'Loaded compilation database( \(auto\))? from [^ ]+' "$LOG" |
        sed -E 's/^Loaded compilation database( \(auto\))? from //' | head -n 1)"
    if [ -z "$loaded_db" ]; then
        if grep -q 'Failed to find compilation database' "$LOG"; then
            fail "clangd did not load any compilation database"
        else
            fail "clangd did not report loading compile_commands.json"
        fi
        hint "check how the editor starts clangd (cwd / --compile-commands-dir)"
    elif [ "$(cd "$(dirname "$loaded_db")" 2>/dev/null && pwd -P)" = "$ROOT_PHYS" ]; then
        ok "clangd loaded the workspace database"
    else
        fail "clangd loaded a different database: $loaded_db"
        hint "expected the one at $ROOT/compile_commands.json"
    fi

    while IFS= read -r cfg; do
        [ -n "$cfg" ] || continue
        info "config: $cfg"
    done < <(grep -oE 'Loading config file at [^ ]+' "$LOG" |
        sed -E 's/^Loading config file at //')

    # Every path the compiler front end will actually search.
    probe_path() { # <ERE> <sed strip> <label> <missing level: fail|warn>
        local pattern="$1" strip="$2" label="$3" level="${4:-warn}"
        local line found=0
        while IFS= read -r line; do
            [ -n "$line" ] || continue
            found=1
            if [ -e "$line" ]; then
                ok "$label: $line"
            elif [ "$level" = "fail" ]; then
                fail "$label does not exist: $line"
                hint "clangd looks for builtin headers and libc++ here"
            elif [ -n "$isysroot_val" ] && [ ! -e "$isysroot_val" ] &&
                [ "${line#"$isysroot_val"/}" != "$line" ]; then
                info "$label $line (covered by the missing isysroot above)"
            else
                case "$line" in
                */usr/local/include)
                    # clang injects this even though no macOS SDK has that dir.
                    info "$label $line is missing but that is normal on macOS"
                    ;;
                *)
                    warn "$label does not exist: $line"
                    hint "clangd searches this path for headers"
                    ;;
                esac
            fi
        done < <(grep -oE -- "$pattern" "$LOG" | sed -E "$strip" | sort -u)
        if [ "$found" -eq 0 ]; then
            info "$label not overridden (clangd uses its built-in default)"
        fi
    }

    resdir="$(grep -oE -- '-resource-dir[= ][^ ]+' "$LOG" |
        sed -E 's/^-resource-dir[= ]//' | sort -u | head -n 1)"
    isysroot_val="$(grep -oE -- '-isysroot [^ ]+' "$LOG" |
        sed -E 's/^-isysroot //' | sort -u | head -n 1)"

    probe_path '-resource-dir[= ][^ ]+' 's/^-resource-dir[= ]//' "resource-dir" fail
    probe_path '-isysroot [^ ]+' 's/^-isysroot //' "isysroot" fail
    probe_path '-internal-isystem [^ ]+' 's/^-internal-isystem //' "internal-isystem"
    probe_path '-internal-externc-isystem [^ ]+' 's/^-internal-externc-isystem //' "internal-externc-isystem"
    probe_path '-fsanitize-system-ignorelist=[^ ]+' 's/^-fsanitize-system-ignorelist=//' "asan ignorelist"

    # The real signal: does the selected resource dir still ship builtin headers?
    if [ -n "$resdir" ]; then
        if [ -e "$resdir/include/stddef.h" ]; then
            ok "resource-dir ships builtin headers: $resdir/include/stddef.h"
        else
            fail "resource-dir has no builtin headers: $resdir/include/stddef.h"
            hint "this is what produces 'unknown type name size_t/__uint32_t'"
        fi
        res_ver="$(basename "$resdir")"
        case "$res_ver" in
        "" | *[!0-9]*) res_ver="" ;;
        esac
        if [ -n "$res_ver" ] && [ -n "$CLANGD_MAJOR" ] && [ "$res_ver" != "$CLANGD_MAJOR" ]; then
            warn "resource-dir is clang $res_ver but clangd is $CLANGD_MAJOR"
            hint "parsing another generation's headers can produce phantom diagnostics"
        fi
    fi

    # Diagnostics, minus clangd's own --check tweak probing noise.
    real_errs="$(grep -E '^E\[' "$LOG" | grep -v 'tweak:' || true)"
    real_n="$(printf '%s' "$real_errs" | grep -c . || true)"
    tweak_n="$(grep -cE '^E\[.*tweak:' "$LOG" || true)"
    if [ "$real_n" -eq 0 ]; then
        ok "clangd reports no diagnostics for the probe file"
    else
        fail "clangd reports $real_n diagnostic(s) for the probe file"
        printf '%s\n' "$real_errs" |
            sed -E 's/^E\[[0-9:.]+\] //' |
            head -n 10 |
            while IFS= read -r l; do info "$l"; done
        hint "if these look nonsensical, the path checks above are the cause"
    fi
    if [ "$tweak_n" -gt 0 ]; then
        info "($tweak_n 'tweak:' probe failures hidden; clangd --check only, not an LSP error)"
    fi
fi

# ========================================================= 5. clangd config files
section 5 6 "clangd config files"

cfg_files=()
[ -f ".clangd" ] && cfg_files+=(".clangd")
[ -f ".clangd.yaml" ] && cfg_files+=(".clangd.yaml")
if [ "$(uname -s)" = "Darwin" ] && [ -z "${XDG_CONFIG_HOME:-}" ]; then
    cfg_files+=("$HOME/Library/Preferences/clangd/config.yaml")
fi
# Always at least this one, which also keeps "${cfg_files[@]}" safe under
# `set -u` on bash 3.2 (an empty array expansion there is a fatal error).
cfg_files+=("${XDG_CONFIG_HOME:-$HOME/.config}/clangd/config.yaml")

for cfg in "${cfg_files[@]}"; do
    [ -f "$cfg" ] || continue
    kv "config" "$cfg"

    # A duplicate top-level key makes clangd discard the file's overrides.
    dupes="$(grep -E '^[A-Za-z_][A-Za-z0-9_]*:' "$cfg" |
        sed -E 's/:.*//' | sort | uniq -d | tr '\n' ' ')"
    dupes="${dupes% }"
    if [ -n "$dupes" ]; then
        warn "duplicate top-level key(s) in $(basename "$cfg"): $dupes"
        hint "clangd may drop the file's overrides entirely; merge them"
    fi

    # Hard-coded, versioned paths: the failure mode this script exists for.
    while IFS= read -r p; do
        [ -n "$p" ] || continue
        if [ -e "$p" ]; then
            case "$p" in
            */lib/clang/*)
                v="$(printf '%s' "$p" | sed -E 's#.*/lib/clang/([0-9]+).*#\1#')"
                if [ -n "$CLANGD_MAJOR" ] && [ "$v" != "$CLANGD_MAJOR" ]; then
                    warn "hard-coded resource-dir is clang $v but clangd is $CLANGD_MAJOR: $p"
                else
                    warn "hard-coded resource-dir: $p"
                fi
                hint "a versioned path like this breaks on the next llvm upgrade; drop it"
                ;;
            *)
                ok "referenced path exists: $p"
                ;;
            esac
        else
            case "$p" in
            */lib/clang/*)
                fail "referenced resource-dir does not exist: $p"
                hint "the toolchain that owned this path was upgraded; delete the entry"
                hint "clangd then falls back to its own resource-dir, which is correct"
                ;;
            *)
                fail "referenced path does not exist: $p"
                hint "point it at an existing path, or delete the entry"
                ;;
            esac
        fi
    done < <(grep -oE -- '-resource-dir=[^ "]+|-isysroot[[:space:]]+[^ "]+|--sysroot=[^ "]+|[^ "]*lib/clang/[0-9]+[^ "]*' "$cfg" |
        sed -E 's/^-resource-dir=//; s/^-isysroot[[:space:]]+//; s/^--sysroot=//' | sort -u)

    while IFS= read -r cpath; do
        [ -n "$cpath" ] || continue
        if [ -x "$cpath" ]; then
            cver="$("$cpath" --version 2>/dev/null | head -n 1)"
            ok "Compiler exists: $cpath ($cver)"
        else
            fail "Compiler is missing or not executable: $cpath"
            hint "point it at an existing compiler, or delete the Compiler entry"
        fi
    done < <(grep -E '^[[:space:]]*Compiler:' "$cfg" |
        sed -E 's/^[[:space:]]*Compiler:[[:space:]]*//' | sort -u)
done

# ================================================================= 6. verdict
section 6 6 "verdict"

printf '       %s%d ok, %d warn, %d fail%s\n' "$C_DIM" "$OK_N" "$WARN_N" "$FAIL_N" "$C_RST"

if [ "$FAIL_N" -eq 0 ] && [ "$WARN_N" -eq 0 ]; then
    printf '\n  %sAll checks passed.%s\n' "$C_OK" "$C_RST"
    info "If the editor still complains, restart the LSP client and re-run."
elif [ "$FAIL_N" -eq 0 ]; then
    printf '\n  %sNo failures, %d warning(s).%s\n' "$C_WARN" "$WARN_N" "$C_RST"
    info "Warnings are usually stale or version-pinned settings; fix them soon."
else
    printf '\n  %s%d failure(s), %d warning(s).%s\n' "$C_FAIL" "$FAIL_N" "$WARN_N" "$C_RST"
    printf '  %sSuggested order:%s\n' "$C_DIM" "$C_RST"
    step=1
    printf '    %d. fix every item marked "fail" above (clangd configs live outside this repo)\n' "$step"
    step=$((step + 1))
    if [ -n "$python3" ]; then
        printf '    %d. bazel build //cpp/... && bazel run //:refresh_compile_commands\n' "$step"
        step=$((step + 1))
    fi
    printf '    %d. restart the LSP client, then re-run this script\n' "$step"
    if [ "$DB_FAIL" -eq 0 ]; then
        info "the database section passed, so the rebuild step is likely optional"
    fi
fi

[ "$FAIL_N" -eq 0 ] || exit 1
exit 0
