// Copyright (c) 2026 The Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Authors: liubang (it.liubang@gmail.com)
// Created: 2026/08/04

// Package server is the REST+SSE transport adapter (#1) over
// app.SessionService (docs/SERVE_DESIGN.md §5): it only authenticates,
// decodes parameters, maps typed errors to status codes, and formats SSE —
// all protocol semantics live in the application layer.
package server

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/liubang/playground/go/pl/loom/internal/app"
	"github.com/liubang/playground/go/pl/loom/internal/server/web"
)

// ProtocolVersion is the wire protocol major version (docs/SERVE_DESIGN.md
// §5.5): breaking changes bump it (and the /vN prefix).
const ProtocolVersion = 1

// maxSSEPerSession bounds concurrent event streams per session
// (docs/SERVE_DESIGN.md §7.2).
const maxSSEPerSession = 8

// maxBodyBytes bounds REST request bodies (prompts may paste large text).
const maxBodyBytes = 4 << 20

// Config configures a Server.
type Config struct {
	// Listen is "host:port" (TCP, loopback recommended) or
	// "unix:/path/to.sock" (UDS).
	Listen string
	// Token is the resolved bearer token (already loaded/generated by the
	// caller); required.
	Token string
	// AllowOrigin, when non-empty, is echoed as Access-Control-Allow-Origin;
	// empty denies all cross-origin requests (the default).
	AllowOrigin string
	// NoWeb disables the embedded SPA (pure API mode, docs/WEB_DESIGN.md §7.1).
	NoWeb bool
	// Version is the build version reported by /v1/meta/version.
	Version string
	// Service is the application layer.
	Service *app.SessionService
	// Logger receives server logs; nil uses slog.Default.
	Logger *slog.Logger
	// AuditLogger receives the audit stream (session/prompt/approval
	// lifecycle); nil falls back to Logger.
	AuditLogger *slog.Logger
}

// Server is the REST+SSE transport adapter.
type Server struct {
	cfg      Config
	svc      *app.SessionService
	logger   *slog.Logger
	audit    *slog.Logger
	instance string

	http     *http.Server
	listener net.Listener

	drainingFlagMu sync.RWMutex
	drainingFlag   bool

	// done closes when Shutdown begins: SSE handlers watch it to emit
	// server.draining and return promptly — http.Server.Shutdown alone
	// never cancels in-flight long-polling requests, so without this
	// signal a live SSE client would stall the graceful stop until the
	// deadline (docs/SERVE_DESIGN.md §7.3).
	done     chan struct{}
	doneOnce sync.Once

	sseMu    sync.Mutex
	sseConns map[string]int
}

// New creates the server (no listening yet).
func New(cfg Config) (*Server, error) {
	if cfg.Service == nil {
		return nil, errors.New("server: SessionService is required")
	}
	if cfg.Token == "" {
		return nil, errors.New("server: token is required")
	}
	if cfg.Listen == "" {
		cfg.Listen = "127.0.0.1:7680"
	}
	logger := cfg.Logger
	if logger == nil {
		logger = slog.Default()
	}
	audit := cfg.AuditLogger
	if audit == nil {
		audit = logger
	}
	var instanceBytes [4]byte
	if _, err := rand.Read(instanceBytes[:]); err != nil {
		return nil, fmt.Errorf("generate instance id: %w", err)
	}
	s := &Server{
		cfg:      cfg,
		svc:      cfg.Service,
		logger:   logger,
		audit:    audit,
		instance: hex.EncodeToString(instanceBytes[:]),
		done:     make(chan struct{}),
		sseConns: make(map[string]int),
	}
	mux := http.NewServeMux()
	s.routes(mux)
	s.http = &http.Server{
		Handler:           s.withMiddleware(mux),
		ReadHeaderTimeout: 10 * time.Second,
		MaxHeaderBytes:    1 << 20,
	}
	return s, nil
}

// Instance returns the server's instance ID: SSE clients resync whenever it
// changes between connections (sequence-space reset detection).
func (s *Server) Instance() string { return s.instance }

// Handler exposes the fully-middlewared HTTP handler — for embedding the
// adapter in-process (tests, future mounts) without a listener.
func (s *Server) Handler() http.Handler { return s.http.Handler }

// Listen binds the configured address (TCP or UDS) without serving.
func (s *Server) Listen() error {
	if strings.HasPrefix(s.cfg.Listen, "unix:") {
		path := strings.TrimPrefix(s.cfg.Listen, "unix:")
		// The data-dir flock (taken by the caller) guarantees the socket is
		// stale when we get here.
		_ = removeSocket(path)
		ln, err := net.Listen("unix", path)
		if err != nil {
			return fmt.Errorf("listen %s: %w", s.cfg.Listen, err)
		}
		if err := chmodSocket(path); err != nil {
			_ = ln.Close()
			return err
		}
		s.listener = ln
		return nil
	}
	ln, err := net.Listen("tcp", s.cfg.Listen)
	if err != nil {
		return fmt.Errorf("listen %s: %w", s.cfg.Listen, err)
	}
	s.listener = ln
	return nil
}

// Addr returns the bound address for logs and client hints.
func (s *Server) Addr() string {
	if s.listener == nil {
		return s.cfg.Listen
	}
	return s.listener.Addr().String()
}

// Serve blocks until the server stops (Shutdown or listener error).
func (s *Server) Serve() error {
	if s.listener == nil {
		return errors.New("server: Listen must be called before Serve")
	}
	s.logger.Info("loom serve listening", "addr", s.Addr(), "instance", s.instance)
	err := s.http.Serve(s.listener)
	if errors.Is(err, http.ErrServerClosed) {
		return nil
	}
	return err
}

// Shutdown gracefully stops the HTTP server: it marks the server draining
// (new sessions/prompts then get 503 via the application layer's own
// draining), signals SSE streams to emit server.draining and return, then
// closes idle connections. Shutdown is idempotent.
func (s *Server) Shutdown(ctx context.Context) error {
	s.drainingFlagMu.Lock()
	s.drainingFlag = true
	s.drainingFlagMu.Unlock()
	s.doneOnce.Do(func() { close(s.done) })
	return s.http.Shutdown(ctx)
}

// shuttingDown reports whether Shutdown has begun (SSE handlers select on
// the done channel it closes).
func (s *Server) shuttingDown() <-chan struct{} { return s.done }

func (s *Server) draining() bool {
	s.drainingFlagMu.RLock()
	defer s.drainingFlagMu.RUnlock()
	return s.drainingFlag
}

func (s *Server) routes(mux *http.ServeMux) {
	mux.HandleFunc("GET /healthz", s.handleHealthz)
	mux.HandleFunc("GET /readyz", s.handleReadyz)
	mux.HandleFunc("GET /v1/meta/version", s.handleMetaVersion)
	mux.HandleFunc("GET /v1/meta/models", s.handleMetaModels)
	mux.HandleFunc("GET /v1/workspaces", s.handleListWorkspaces)
	mux.HandleFunc("POST /v1/workspaces", s.handleRegisterWorkspace)
	mux.HandleFunc("GET /v1/workspaces/{id}", s.handleGetWorkspace)
	mux.HandleFunc("DELETE /v1/workspaces/{id}", s.handleDeleteWorkspace)
	mux.HandleFunc("GET /v1/files/browse", s.handleBrowseDirectories)
	mux.HandleFunc("GET /v1/sessions", s.handleListSessions)
	mux.HandleFunc("POST /v1/sessions", s.handleCreateSession)
	mux.HandleFunc("GET /v1/sessions/{id}", s.handleInspectSession)
	mux.HandleFunc("POST /v1/sessions/{id}/archive", s.handleArchiveSession)
	mux.HandleFunc("DELETE /v1/sessions/{id}", s.handleDeleteSession)
	mux.HandleFunc("GET /v1/sessions/{id}/transcript", s.handleTranscript)
	mux.HandleFunc("GET /v1/sessions/{id}/snapshot", s.handleSnapshot)
	mux.HandleFunc("POST /v1/sessions/{id}/prompts", s.handleSubmitPrompt)
	mux.HandleFunc("POST /v1/sessions/{id}/cancel", s.handleCancelTurn)
	mux.HandleFunc("POST /v1/sessions/{id}/feedback", s.handleSubmitFeedback)
	mux.HandleFunc("POST /v1/sessions/{id}/approvals/{approvalID}", s.handleResolveApproval)
	mux.HandleFunc("POST /v1/sessions/{id}/questions/{questionID}", s.handleAnswerQuestion)
	mux.HandleFunc("POST /v1/sessions/{id}/model", s.handleSetModel)
	mux.HandleFunc("POST /v1/sessions/{id}/reasoning", s.handleSetReasoning)
	mux.HandleFunc("POST /v1/sessions/{id}/compact", s.handleRequestCompaction)
	mux.HandleFunc("GET /v1/sessions/{id}/events", s.handleSessionEvents)
	mux.HandleFunc("GET /v1/artifacts/{id}", s.handleArtifact)
	// Share links: create/revoke are owner operations (bearer-gated);
	// the /v1/shared/* reads and the /share/{token} page are public —
	// the unguessable token in the URL is the capability.
	mux.HandleFunc("POST /v1/sessions/{id}/share", s.handleShareSession)
	mux.HandleFunc("DELETE /v1/sessions/{id}/share", s.handleRevokeShare)
	mux.HandleFunc("GET /v1/shared/{token}", s.handleSharedView)
	mux.HandleFunc("GET /v1/shared/{token}/artifacts/{id}", s.handleSharedArtifact)
	if !s.cfg.NoWeb {
		mux.Handle("GET /share/{token}", web.SharePageHandler())
	}
	if !s.cfg.NoWeb {
		// Catch-all for the embedded SPA; ServeMux gives the /v1 patterns
		// precedence (docs/WEB_DESIGN.md §7.1).
		mux.Handle("GET /", web.Handler())
	}
}

// withMiddleware chains auth, body limits, CORS denial, and panic
// containment around the router.
func (s *Server) withMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Security headers on every response, static and API alike
		// (docs/WEB_DESIGN.md §7.2): CSP is the second XSS line of defense
		// behind DOMPurify; X-Frame-Options blocks clickjacking.
		header := w.Header()
		// img-src allows blob: because artifact images are fetched with the
		// bearer token and rendered through URL.createObjectURL — <img> cannot
		// carry the Authorization header itself (see artifactBlock).
		header.Set("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'")
		header.Set("X-Content-Type-Options", "nosniff")
		header.Set("Referrer-Policy", "no-referrer")
		header.Set("X-Frame-Options", "DENY")
		// CORS: deny cross-origin by default (no ACAO header at all);
		// --allow-origin whitelists one origin for remote-frontend
		// development (docs/SERVE_DESIGN.md §5.2).
		if origin := r.Header.Get("Origin"); origin != "" && s.cfg.AllowOrigin != "" && origin == s.cfg.AllowOrigin {
			w.Header().Set("Access-Control-Allow-Origin", origin)
		}
		// The SPA's static assets are not sensitive: the token gate page
		// must be reachable anonymously, and every /v1 endpoint still
		// requires the bearer token (docs/WEB_DESIGN.md §7.1).
		if !isHealthRoute(r.URL.Path) && !isStaticRoute(r.URL.Path) && !isSharedRoute(r.URL.Path) && !s.authorized(r) {
			writeError(w, errUnauthorized)
			return
		}
		next.ServeHTTP(w, r)
	})
}

func isHealthRoute(path string) bool {
	return path == "/healthz" || path == "/readyz"
}

// isStaticRoute reports whether the path targets the embedded SPA rather
// than the API.
func isStaticRoute(path string) bool {
	return !strings.HasPrefix(path, "/v1/")
}

// isSharedRoute reports whether the path is a public share-link read: the
// 128-bit token embedded in the URL is the credential, so these routes
// skip bearer auth (read-only by construction).
func isSharedRoute(path string) bool {
	return strings.HasPrefix(path, "/v1/shared/")
}

// acquireSSE registers one SSE connection for the session; false when the
// per-session cap is reached.
func (s *Server) acquireSSE(id string) bool {
	s.sseMu.Lock()
	defer s.sseMu.Unlock()
	if s.sseConns[id] >= maxSSEPerSession {
		return false
	}
	s.sseConns[id]++
	return true
}

func (s *Server) releaseSSE(id string) {
	s.sseMu.Lock()
	defer s.sseMu.Unlock()
	if s.sseConns[id] <= 1 {
		delete(s.sseConns, id)
		return
	}
	s.sseConns[id]--
}

func (s *Server) handleHealthz(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
}

func (s *Server) handleReadyz(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
}

func (s *Server) handleMetaVersion(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{
		"protocol": ProtocolVersion,
		"version":  s.cfg.Version,
		"instance": s.instance,
	})
}

// handleMetaModels serves the model catalog for frontend pickers.
func (s *Server) handleMetaModels(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, s.svc.ModelCatalog())
}
