---
name: build-python
on:
  push:
    branches:
      - main
    paths:
      - "MODULE.bazel"
      - "MODULE.bazel.lock"
      - ".bazelrc"
      - "bazel/**"
      - "python/**"
      - ".github/workflows/build_python.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-python:
    name: python playground
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          repository-cache: true
          disk-cache: ${{ github.workflow }}-${{ runner.os }}
      - name: build and test
        run: |
          bazel test --config=ci //python/...
