---
name: build-go
on:
  push:
    branches:
      - main
    paths:
      - "MODULE.bazel"
      - "go/**"
      - ".github/workflows/build_go.yml"
  workflow_dispatch:

jobs:
  build-go:
    name: go playground
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          repository-cache: true
          disk-cache: ${{ github.workflow }}-${{ runner.os }}

      - name: build and test
        run: |
          bazel build --disk_cache=${{ github.workflow }}-${{ runner.os }} //go/...
          bazel test --disk_cache=${{ github.workflow }}-${{ runner.os }} //go/...
