---
name: build-cpp
on:
  push:
    branches:
      - main
    paths:
      - "MODULE.bazel"
      - "cpp/**"
      - ".github/workflows/build_cpp.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-macos:
    name: test-macos
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          repository-cache: true
          disk-cache: ${{ github.workflow }}-${{ runner.os }}
      - name: Cache Homebrew packages
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew
            /opt/homebrew/Cellar/llvm
            /opt/homebrew/Cellar/nasm
            /opt/homebrew/Cellar/libomp
          key: ${{ runner.os }}-brew-llvm-nasm-libomp-${{ hashFiles('.github/workflows/build_cpp.yml') }}
          restore-keys: |
            ${{ runner.os }}-brew-llvm-nasm-libomp-
      - run: |
          brew install llvm
          brew install nasm
          brew install libomp
      - name: run test
        run: |
          bazel test \
            --config=release \
            //cpp/...
  test-linux:
    strategy:
      matrix:
        compiler:
          [
            { name: gcc, flag: --action_env=CC=gcc-14 --linkopt=-fuse-ld=gold },
            {
              name: clang,
              flag: --action_env=CC=clang-18 --cxxopt=-stdlib=libstdc++ --cxxopt=-Wno-error=unused-but-set-variable --cxxopt=-Wno-error=unused-but-set-parameter --linkopt=-stdlib=libstdc++,
            },
          ]
    name: test-linux
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          repository-cache: true
          disk-cache: ${{ github.workflow }}-${{ runner.os }}-${{ matrix.compiler.name }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y nasm libomp-dev lcov
      - name: run test
        run: |
          bazel test \
            --config=release \
            ${{ matrix.compiler.flag }} \
            //cpp/...
  coverage:
    name: coverage
    runs-on: ubuntu-24.04
    needs: [test-macos, test-linux]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          repository-cache: true
          disk-cache: ${{ github.workflow }}-${{ runner.os }}-gcc
      - run: |
          sudo apt-get update
          sudo apt-get install -y nasm libomp-dev lcov
      - name: run coverage
        run: |
          bazel coverage \
            --config=release \
            --action_env=CC=gcc-14 \
            --verbose_failures \
            --combined_report=lcov \
            --instrument_test_targets \
            //cpp/...
          ls -lh ./bazel-out/_coverage/_coverage_report.dat
          genhtml --ignore-errors negative --output coverage ./bazel-out/_coverage/_coverage_report.dat
          cp -r ./registry ./coverage/
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          publish_branch: coverage
          user_name: "liubang"
          user_email: "it.liubang@gmail.com"
