#======================================================================
#
# BUILD -
#
# Created by liubang on 2023/05/21 22:39
# Last Modified: 2023/05/21 22:39
#
#======================================================================

cc_library(
    name = "hash",
    hdrs = glob(["*.h"]),
    copts = ["-std=c++17"],
    visibility = ["//visibility:public"],
)
